# Generated by Django 4.2.3 on 2023-07-05 17:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("panel", "0002_alter_location_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="location",
            table="location",
        ),
    ]
